#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

export RACK_ENV='test'

echo '--- source config'
set -o allexport
source .env
set +o allexport

echo '--- run bundler'
bundle install

echo '--- run specs'
./bin/rspec
