#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

echo "--- Preparing environment variables"
export RACK_ENV="test"
set -o allexport
source .env
set +o allexport

echo "--- Installing gems"
bundle install

echo "+++ Running tests"
bin/rspec
